### ISSUE TITLE
CompartmentReportView crash

### ISSUE THREAD

**Issue by arsenius7** [BlueBrain/Brion#215]
When I use `CompartmentReportView.load(t_start, t_end, t_step)` with `t_end < t_step` I'm getting Python session crash:

```
>>> import brain
>>> rep = brain.CompartmentReport('/gpfs/bbp.cscs.ch/project/proj66/circuits/O1/20180305/simulations/002/soma.h5')
>>> rep.create_view([229]).load(0, 0.01, 0.1)
Floating point exception (core dumped)
```

**Comment by hernando** [comment]
I assume that this is using the OS/X wheel, but could you please confirm?

**Comment by arsenius7** [comment]
I've checked both OS/X wheel and Linux one.

**Comment by arsenius7** [comment]
Yes, having ``t_end < t_step`` makes no sense.
But hard-crash might be too of a punishment for that. :)

**Comment by hernando** [comment]
In fact it shoulnd't crash at all, but just return you one frame

**Comment by arsenius7** [comment]
Yes, given that report time step is itself `0.1` I would expect same behavior as
```
load(0, 0.01)
```
with `t_step` argument omitted (this one works fine).

**Comment by hernando** [comment]
I found what caused the exception, but I still don't know why no frames were returned.
I have one question for the exceptional case of returning no data. What do you prefer to get as a result in this case:
* None
* (None, None)
* (numpy.array([], dtype=float), numpy.array([], dtype=float))
I'd vote for the second one, because with option one this:

     timestamps, frames = view.load(begin, end, step)

throws when the result is empty and option three looks a bit cumbersome.

**Comment by arsenius7** [comment]
I would prefer (3) if empty return result is considered "normal" by `brain`, or an exception instead of returning None(s) otherwise.
