### ISSUE TITLE
Sort compartment IDs in `brain.CompartmentReportMapping`?

### ISSUE THREAD

**Issue by arsenius7** [BlueBrain/Brion#246]
When I check compartment ID mapping for some report, I see that compartment IDs appear shuffled:
```
>> import brain
>> rep = brain.CompartmentReport('/gpfs/bbp.cscs.ch/project/proj32/bioSTDP/v2/step6_network/simulations/dotstim/naivecircuit/plasticityfunc/stimulus0/seed166273/part1/rho.bbp')
>> rep.create_view([341]).mapping.index
array([(341, 255), (341, 254), (341, 253), (341, 393), ...])
```
On the other hand, "raw" dump shows compartment IDs in sorted order:
```
$ module load nix/hpc/reportinglib/2.4.2-2018.07
$ fullDump /gpfs/bbp.cscs.ch/project/proj32/bioSTDP/v2/step6_network/simulations/dotstim/naivecircuit/plasticityfunc/stimulus0/seed166273/part1/rho.bbp 341 | head -4
...
30 31 40 41 42 58 59 ...
```

Does `brain.CompartmentReport` preserve mapping order from the raw file? Is it possible to ensure compartment IDs appear in sorted order (and shuffle data view accordingly)?

**Comment by hernando** [comment]
Based on the same of the report, I think those IDs are not compartments or sections, but a kind of synapse ID.

The order reported by mapping.index is the order in which those elements appear in the file itself. Brion will never resort the data because that's inefficient. @jplanasc mentioned to me a similar issue months ago and I Brion should be correct and not be shuffling anything within a cell (cells may be resorted if you ask for a subset though). Your output from reporting lib is too short to mean anything to me. It could also be that reporting lib is sorting the buffer after reading.

Your actual problem is that you don't like the index being out of order or that the values in the buffer don't seem to relate to the elements pointed by the index?

**Comment by arsenius7** [comment]
> Your actual problem is that you don't like the index being out of order or that the values in the buffer don't seem to relate to the elements pointed by the index?

Unsorted order made me naturally worry about correspondence between mapping and index.

Since you confirm that it's not an issue, sorted order becomes merely a question of "user convenience" (sorted order of compartment / synapse IDs looks arguably better for table data view). I guess I can as well do it on BluePy side.

Maybe it's worth stating somewhere that for the sake of efficiency CompartmentReport preserves raw data order (sorry, I have not checked the code yet).

**Comment by hernando** [comment]
Just to confirm that the disparity is not actually a bug, could you check with somebody else what is reporting lib doing?

**Comment by arsenius7** [comment]
Ergh... OK, I'll try. ^^

**Comment by arsenius7** [comment]
In your opinion, does it worth the trouble to introduce a similar `sortData` parameter for `CompartmentReportView`, which will sort mapping and re-shuffle data accordingly (defaulting it to `false` if you prefer)?

**Comment by hernando** [comment]
I don't think it's worth it. I'd never use it as it would incur a hidden cost which is difficult to quantify.  Another reason against it is that users may start to rely inadvertently on the assumption that the buffer is sorted (it already happens). But that's just my opinion, you should ask users.

The HDF5 representation is probably sorted in the file itself as well, but this is not a requirement.

**Comment by arsenius7** [comment]
OK, let's leave it be then.
I'll sort the data from BluePy side, should I get such a request.
