### ISSUE TITLE
Python 3.8 and beyond wheels

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/Brion#291]
The last couple of days at least 2 people had problems installing Brain because there is no wheel available for python 3.8. Could you build wheels for python versions > 3.7
Thanks.

**Comment by wvangeit** [comment]
Is there any ETA for this? Thanks.

**Comment by NadirRoGue** [comment]
Hello, 
It will be done shortly.

**Comment by wvangeit** [comment]
👍

**Comment by wvangeit** [comment]
Is there any ETA for this?

**Comment by NadirRoGue** [comment]
The initial release has already been made
https://pypi.org/project/Brion/

We are waiting to merge the last update so we can enable the wheels auto-updating repository

**Comment by wvangeit** [comment]
Any updates?

**Comment by NadirRoGue** [comment]
The last changes needed for Brion have already been merged. The automatic update is almost ready in the Brion-wheel repository, however there is a problem: Brion's python package is called brain (because underneath it uses Brion's high level library 'Brain'), which is conflicting with an existing project in PyPi (https://pypi.org/project/brain/)

**Comment by ppodhajski** [comment]
you can install in development verion with:
```pip3 install brion==3.3.1.dev0 ```

3.3.1 release will follow soon

**Comment by wvangeit** [comment]
Ok, thanks !

**Comment by jplanasc** [comment]
Latest wheels available on:
https://pypi.org/project/brion/
