### ISSUE TITLE
Brion morphology section types not fully compatible with SWC "spec"

### ISSUE THREAD

**Issue by juanchopanza** [BlueBrain/Brion#9]
The Brion morphology types defined in brion/enums.t `brion::enums::SectionType` do not match the ones defined in the SWC "specification", e.g. http://research.mssm.edu/cnic/swc.html:

```
    0 = undefined
    1 = soma
    2 = axon
    3 = dendrite
    4 = apical dendrite
    5 = fork point
    6 = end point
    7 = custom
```

Since the types are checked when parsing SWC files, valid files fail to parse. See for example `test_data/swc/sequential_trunk_off_1_16pt.swc` in [hbp-neurom's test data directory](https://bbpcode.epfl.ch/code/gitweb?p=algorithms/hbp-neurom.git;a=tree;f=test_data/swc;h=85e1e786fd29551140487736e948045c0058b147;hb=HEAD) (access to bbpcode.epfl.ch required.) In fact, all the `test_data/swc/sequential_trunk_off*.swc` are valid SWC.

**Comment by hernando** [comment]
The enum in Brion is missing the types fork point, end point and custom. It's hard to decide what to do with this points and I don't understand why they were added to the specification in the first place, specially the end point (why these widespread standard file formats in Biology are so badly designed?). End points and fork points are implicit to the structure, making it optional to make them explicit only leaves room for consistency errors in my opinion.
I see that for branch points it might not be fully clear to which type they belong and hence the additional of a fork point, but for end points there should be no discussion. Then, what's the difference between undefined and custom? Having only one custom identifier is sort of useless.

I could add the extra types to the enum, but then we have to decide to do with them when they appear. Most probably this addition may break code with uses switch statements.

Regarding the example file. It may be syntactically correct, but not semantically for a few reasons. The most obvious are:
- The end point with id 7 is not and end point
- The fork points at ids 6 and 14 are have only one children, so they are not fork points (unless the for point tag actually means "hey, here there is a forking, but I don't care about one of the branches".
- Some section type transitions are biologically impossible: axon->dendrite, x->soma.
I don't know what sanity checks are implemented in MorphM, but I decided several in Brion, and following the same principle, consistency rules for the new types will be broken by this file. Giving up the sanity checks it's calling for trouble. In my opinion, bad input files should be detected as soon as possible (I can't remember how many times I've been blamed for errors that could be backtracked to the data).
That means that it won't be safe to simply add the new section types.

**Comment by hernando** [comment]
Another comment. Despite SWC allows it, Brion doesn't allow having multiple somas in a single file. SWC is far too relaxed in many senses, so we should agree whether we are going to accept all the potentially quirky input files or enforce a collection of sensible rules that are checked at parsing time.

**Comment by juanchopanza** [comment]
We're also missing section type 0, i.e. "undefined". The brion parser does not accept that. Concerning the sample file, it is true it isn't semantically correct. It only contains valid SWC types chosen cyclically. It is valid SWC as far as the "spec" goes. Does Brion impose some semantic constraints on top of that?

I agree that it doesn't make much sense to have fork points and end-points, but if they are in the "spec" perhaps we should at least allow them. We have to figure out if they are used, but I suspect even if they are they could be replaced by one of the other types. But at the very least, I think "undefined" should be allowed.

**Comment by hernando** [comment]
Brion does some semantic verifications, some of them are:
- There's one and only one soma polyline or point
- Parent point ids exist (no dangling branches)
- If the section type changes along a path, the point at which the change occurs starts a new section.
Then, Brion doesn't check this, but If I remember correctly client code in BBPSDK verifies the correctness of section types on the tree.

For fork points and end points I will assign the parent type during parsing if you're OK with that. I don't think these points need to recognized as explicit section types. I guess they were added to facilitate some processes by not require the full parsing and tree construction, but that's not a problem for Brion because it parses the whole file and then creates the tree in any case.

The problem of undefined section types is that BBPSDK won't know what to do with them. But it's probably OK to add it to Brion. BBPSDK will throw if it finds it.

What do we do with custom?

**Comment by juanchopanza** [comment]
I think it is fine to do what you describe for fork and end-points, but I will cross-check with some scientists. For custom, we could probably leave things as they are for now and open an issue if there is ever a need for that type. And concerning the undefined type, would it make sense to add a "strict" or "bbpsdk" flag to the converter, which sets whether an undefined point is considered an error or not?

**Comment by hernando** [comment]
I would make the option more explicit: allow undefined yes or no

**Comment by juanchopanza** [comment]
Yes, that would work.

**Comment by hernando** [comment]
Should I allow end points which are not end points?

**Comment by juanchopanza** [comment]
That's a good question. Obviously it doesn't make sense, but I wonder if this should be discussed in a broader forum. My personal preference would be for that to be an error, and for the converter to give a clear message to the user. I think the same would apply to fork points that aren't fork points.

**Comment by hernando** [comment]
I have to stop for now. I'm out until Sunday, so I'll resume on Monday.

**Comment by hernando** [comment]
As discussed by e-mail and following Stefan's recommendations I'm going to transform the type of fork and end points into the most reasonable type according to the parent or leave it undefined if there's no choice. I've taken this decision not only to be less pedantic but also because I don't see any added value and it's going to take me more time than simply fixing the points.

I will add the optional throw on undefined nevertheless.

**Comment by hernando** [comment]
Hmm, I'm realizing that I have to change the API in a not so pretty way... so I think that it's better to leave it as is. If we really think this is needed it can be added later on.
