### ISSUE TITLE
morphologyConverter issue with no soma

### ISSUE THREAD

**Issue by eile** [BlueBrain/Brion#98]
From the previous mail thread, it's not clear what the issue is. @markovg, can you add the bug description below?

```
/gpfs/bbp.cscs.ch/project/proj45/ebmuller/TD_bug

module load BBP/viz/2016.R2
morphologyConverter -i artcell_\(1\)_artcell_672_1_smoothed.swc -o
artcell_\(1\)_artcell_672_1_smoothed.h5 -f h5v1

h5dump -d structure artcell_\(1\)_artcell_672_1_smoothed.h5


HDF5 "artcell_(1)_artcell_672_1_smoothed.h5" {
DATASET "structure" {
   DATATYPE  H5T_STD_I32LE
   DATASPACE  SIMPLE { ( 118, 3 ) / ( 118, 3 ) }
   DATA {
   (0,0): 0, 1, -1,
   (1,0): 1, 2, 0,
   (2,0): 2, 2, 1,
   (3,0): 17, 2, 2,
   (4,0): 50, 2, 3,
   (5,0): 204, 2, 3,
   (6,0): 336, 2, 5,

```

**Comment by hernando** [comment]
I could load this in RTNeuron after making a simple modification in the swc file and converting it again to hdf5.

The file that I found at /gpfs/bbp.cscs.ch/project/proj45/ebmuller/TD_bug has a strange feature. If you look at the first 16 points, you can see a single soma point and a single first order axonal section which has just 1 point because there are two sections branching at point 2. This single point section was problematic for BBSDK because it makes some functions raise exceptions. To workaround it, I changed the second point to also be a soma point. This way I could display the tree in RTNeuron (is this a thalamo cortical axon?).

If the actual problem is that the morphology converter complains when there is no soma at all, we have to discuss what is going to be the consumer of the h5 morphology because I think that the morphology classes from BBPSDK and Brain require a soma. Maybe this requirement can be relaxed, but I have the impression that the consumer is some other code that is reading the h5 directly.
A better solution for this scenario would be to add a soma point with the same coordinates as the first axon point instead of converting this point into the soma. For this file in particular, the first two lines would look like this:
4973 1 -55.16300000 -100.00000000 502.63000000   0.13000000 -1
1 2 -55.16300000 -100.00000000 502.63000000   0.13000000 4973
